# Generated by Django 4.2.20 on 2025-04-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profil_image_user_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profil_image',
            new_name='profile_image',
        ),
    ]
