# Generated by Django 4.2.20 on 2025-04-24 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 24, 5, 23, 35, 399760, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
